[colors]
[colors.primary]
background = '#0d1017'
foreground = '#cce0f5'

# Normal colors
[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#89b4f8'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#89b4f8'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

# Selection colors
[colors.selection]
background = '#89b4f8'

# Font configuration
[font]
normal.family = "JetBrainsMono Nerd Font"
size = 18.0
