general {
    col.active_border = 0xff89b4f8
}

decoration {
    rounding = 10
}

group {
    col.border_active          = 0xff89b4f8
    col.border_inactive        = 0xff444b6a
    col.border_locked_active   = 0xff89b4f8
    col.border_locked_inactive = 0xff444b6a
}
